### ISSUE TITLE
Adhere to RFC6749 (support urlencoded basic auth tokens)

### ISSUE THREAD

**Issue by anderaus** [Sbanken/api-examples#11]
If using [IdentityModel](https://github.com/IdentityModel/IdentityModel2) higher than 3.0.0 (in your .net core example you use 3.0.0), most of the Sbanken API client secrets will be denied as they contain special characters like `?`, `+` and `:` that will be urlencoded (but don't seem to be properly decoded in your version of IdentityServer).

This is where the encoding happens:
https://github.com/IdentityModel/IdentityModel2/blob/release/src/IdentityModel/Client/BasicAuthenticationOAuthHeaderValue.cs#L30

Proper decoding seems to have been added in the latest IdentityServer update:
https://github.com/IdentityServer/IdentityServer4/pull/2052

It would be great if you could stop using special characters in the secrets or start supporting urlencoded values.

**Comment by sbankenOB** [comment]
Hi Anderaus, thanks for the input. We are aware of this change in identityModel, and are planning an update to support urlencoded values. Please use v3.0.0 of IdentityModel for now if possible.

**Comment by anderaus** [comment]
Cool, I'll close this issue then. For reference: I have to use >v3.0.0 but was able to work around the problem by overriding IdentityModel's TokenClient and switch to using BasicAuthenticationHeaderValue: https://github.com/anderaus/Sbanken.DotNet/blob/master/src/Sbanken.DotNet/CustomTokenClient.cs#L26
