### ISSUE TITLE
API does not contain string enum values for source

### ISSUE THREAD

**Issue by HNygard** [Sbanken/api-examples#14]
Example transaction v2:

        {
            "transactionId": "X",
            "accountingDate": "2017-10-31T00:00:00+01:00",
            "interestDate": "2017-11-01T00:00:00+01:00",
            "otherAccountNumberSpecified": false,
            "amount": 123.45,
            "text": "KREDITRENTER",
            "transactionType": "KREDITRTE",
            "transactionTypeCode": 752,
            "transactionTypeText": "KREDITRTE",
            "isReservation": false,
            "reservationType": null,
            "source": 1,
            "cardDetailsSpecified": false
        }

Source is the number 1. According to API doc this should be a string with values 'accountStatement' or 'archive'.

**Comment by sbankenOB** [comment]
@HNygard thanks for the input. Confirmed that this is a bug.

**Comment by HNygard** [comment]
Is this fixed?

**Comment by bjartekh** [comment]
The source bug is fixed yes.
