### ISSUE TITLE
Missing documentation on authentication

### ISSUE THREAD

**Issue by SigTill** [Sbanken/api-examples#2]
Missing documentation on authentication - how to get a token

**Comment by aleksen** [comment]
I noticed this as well.
@SigTill I found useful information at https://github.com/Sbanken/api-examples/blob/master/NodeSampleApplication/service/sbankenapi.js

**Comment by anderaus** [comment]
@SigTill you may find my notes from my first test of the api helpful: http://blog.novanet.no/a-first-look-at-the-sbanken-open-banking-api/ 
Let me know if you have any specific questions and I'll try to answer.

**Comment by sbankenOB** [comment]
We have updated the readme with more information about authentication and how to get an access token.
