### ISSUE TITLE
https://api.sbanken.no/identityserver -> HTTP 404

### ISSUE THREAD

**Issue by larsw** [Sbanken/api-examples#24]
:-/

**Comment by LarsErikDahl** [comment]
Try https://api.sbanken.no/identityserver/connect/token. The README.md file explains how to do this in the "How to get an Access Token" section

**Comment by vegar** [comment]
According to the README.md, the host name was changed to https://auth.sbanken.no back in september 2018.

It's a pity that that the example code isn't kept up to date :-/
