### ISSUE TITLE
https://api.sbanken.no/Bank/api/v1/EFakturas yields 403

### ISSUE THREAD

**Issue by aleksen** [Sbanken/api-examples#26]
According to the swagger file this endpoint should work:
https://api.sbanken.no/Bank/swagger/index.html?urls.primaryName=EFakturas%20v1

**Comment by anderaus** [comment]
@aleksen  I sent an email to `api@sbanken.no` pointing out the issue. It seems to have been resolved now.

**Comment by aleksen** [comment]
Thanks!
