### ISSUE TITLE
Lifetime of access token missing in doc.

### ISSUE THREAD

**Issue by peec** [Sbanken/api-examples#4]
The lifetime of the requested access token is not mentioned in doc. 

How long does the access token live ?

**Comment by Pwntus** [comment]
A successful response from the `identity server` yields this:

```
{
  "access_token": "",
  "expires_in": 3600,
  "token_type": "Bearer"
}
```
So I take it that the access token is valid for **1 hour**. Indeed, the `identity server` completely lacks documentation.
