### ISSUE TITLE
Duplicate transactions without transactionid

### ISSUE THREAD

**Issue by aleksen** [Sbanken/api-examples#55]
I'm currently experiencing that the most recent transactions (Last 16 days) have duplicates without transactionId, even though the transactions have been cleared and are not reservations.

**Comment by bjartekh** [comment]
Hei. Vi trenger litt mer informasjon for å kunne feilsøke: Kopi av request uri (inkl. query string) og av JSON resultatet (masker sensitiv informasjon). Du kan sende til api@sbanken.no.

**Comment by aleksen** [comment]
Hei.

Dessverre hadde jeg ikke fått med meg at transactionId var flytta til transactionDetail.transactionId. Alt er normalt igjen nå. :+1:
