### ISSUE TITLE
No swagger documentation on how to get transactionDetails?

### ISSUE THREAD

**Issue by petterdaae** [Sbanken/api-examples#56]
The swagger documentation says that the transactions reponse *can* contain this:
```json
"hasTransactionDetail": true,
"transactionDetail": {
        "formattedAccountNumber": "string",
        "transactionId": 0,
        "cid": "string",
        "amountDescription": "string",
        "receiverName": "string",
        "numericReference": 0,
        "payerName": "string",
        "registrationDate": "2019-07-20T18:14:57.078Z"
}
```
But I have only been able to get reponses with `"hasTransactionDetail": false` and no `transactionDetail`. Am I missing something?

**Comment by aleksen** [comment]
Are you using this endpoint? https://api.sbanken.no/exec.bank/swagger/index.html?urls.primaryName=Transactions%20v1
(Note that the url has changed to exec.bank)

Also. I have noticed that nettgiro and efakturas don't have transactiondetail. Card payments often has it

**Comment by petterdaae** [comment]
Yes, but after reading other issues it seems like some of these things are unavailable (for example transactionid :)).
