### ISSUE TITLE
Nagging about transactionid

### ISSUE THREAD

**Issue by aleksen** [Sbanken/api-examples#57]
Will transactionId be reintroduced in the api sometime? My application is currently useless without transactionids and I believe more people need this feature again. 

Sorry for nagging!

**Comment by esogge** [comment]
Please add a TransactionId. I'm in the same position as aleksen - my application is useless without a unique identifier on the transactions. This is a must in the API.

**Comment by elzapp** [comment]
Transactionid could be added for archived transactions, but it is hard to do for reservations pending transactions (ikke bokført). In fact, if you don't hit the cache with your query, you do get a transactionid in the response. It is however lost in the cache. This is a known issue.

**Comment by eirikraha** [comment]
I would also like to add my voice to this. TransactionID would really help my application.

**Comment by bjartekh** [comment]
TransactionId is now available via a new endpoint (check the OpenAPI spec for the May 2021 release)
