### ISSUE TITLE
Investment accounts - virker ikke, får bare 403 forbidden

### ISSUE THREAD

**Issue by opAmpEng** [Sbanken/api-examples#65]
Selv om alle tilganger er aktivert inne på utviklerportalen så virker det umulig å få ut data om "investment accounts".

Jeg henter ut data om kontoer og transaksjoner fra api.sbanken.no/exec.bank/api/v1/... helt uten problemer. Virker som om det er noe spesielt med api.sbanken.no/exec.customers/api/v1/MyProfiles/...  ??

Har også fått bekreftet dette problemet fra folk som har mer peiling enn meg :-)

Edit: Hvis noen får dette til å virke (dvs. at det bare er meg som roter), så si ifra! :-)

**Comment by elzapp** [comment]
Hei.
Dessverre er ikke dette API-endepunktet en del av de api-endepunktene som kan benyttes med en apibeta-nøkkel. Vi har per i dag ikke noen apibeta endepunkt for fond eller aksjer, og disse endepunktene skulle ikke vært med i den offentlige dokumentasjonen. 

Jeg kjenner ikke til noen umiddelbare planer om å gjøre disse endepunktene tilgjengelig for apibeta-kunder. Dokumentasjonen for dem vil uansett snart bli fjernet inntil videre.

**Comment by bjartekh** [comment]
Vi har utelatt MyProfiles-endepunktet fra oppdatert OpenAPI spec (Mai 2021-oppdatering)
