### ISSUE TITLE
Transfer funker ikke med æøå (og muligens andre tegn)

### ISSUE THREAD

**Issue by halworsen** [Sbanken/api-examples#68]
Gravde frem et gammelt skript som flytter penger mellom to kontoer og klødde meg lenge i hodet over hvorfor det ikke funket. APIet svarer med kode 200 og ingen feilmelding.

Viser seg at overføringen ikke funker dersom meldingen/beskrivelsen inneholder æ, ø eller å, selv om [beskrivelsen av endepunktet påstår at dette er lovlige tegn](https://api.sbanken.no/exec.bank/swagger/index.html?urls.primaryName=Transfers%20v1). Har ikke testet med andre tegn men det er vel rimelig å anta at det ikke går for flere tegn enn bare æøå.

**Comment by bjartekh** [comment]
Heisann, dette skal være fikset i Mai 2021-oppdateringen
